title: Lynn Huang
description: Personal blog
theme: minima
url: https://lynnhuang-peilin.github.io
baseurl: /website

# Optional niceties (all supported on GitHub Pages)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
